/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Settlement {
  export type TradeStruct = {
    fromAmount: BigNumberish;
    toAmount: BigNumberish;
    settlementTime: BigNumberish;
    taker: AddressLike;
    maker: AddressLike;
    fromToken: AddressLike;
    toToken: AddressLike;
    quoteId: BytesLike;
    state: BigNumberish;
  };

  export type TradeStructOutput = [
    fromAmount: bigint,
    toAmount: bigint,
    settlementTime: bigint,
    taker: string,
    maker: string,
    fromToken: string,
    toToken: string,
    quoteId: string,
    state: bigint
  ] & {
    fromAmount: bigint;
    toAmount: bigint;
    settlementTime: bigint;
    taker: string;
    maker: string;
    fromToken: string;
    toToken: string;
    quoteId: string;
    state: bigint;
  };
}

export interface SettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_GRACE_PERIOD"
      | "batchSettle"
      | "cancelTrade"
      | "createTrade"
      | "eip712Domain"
      | "emergencyCancel"
      | "escrowBalances"
      | "fundTrade"
      | "getTrade"
      | "gracePeriod"
      | "isExpired"
      | "owner"
      | "quoteUsed"
      | "refundIfExpired"
      | "remainingToFund"
      | "renounceOwnership"
      | "setGracePeriod"
      | "settle"
      | "tradeCounter"
      | "trades"
      | "transferOwnership"
      | "verifySignatures"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "OwnershipTransferred"
      | "SettleSkipped"
      | "TradeCancelled"
      | "TradeCreated"
      | "TradeFunded"
      | "TradeRefunded"
      | "TradeSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchSettle",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTrade",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyCancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundTrade",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gracePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [Settlement.TradeStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundIfExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingToFund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGracePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySignatures",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSettle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyCancel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundTrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quoteUsed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundIfExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingToFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tradeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySignatures",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettleSkippedEvent {
  export type InputTuple = [tradeId: BigNumberish, reason: string];
  export type OutputTuple = [tradeId: bigint, reason: string];
  export interface OutputObject {
    tradeId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCancelledEvent {
  export type InputTuple = [tradeId: BigNumberish, by: AddressLike];
  export type OutputTuple = [tradeId: bigint, by: string];
  export interface OutputObject {
    tradeId: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCreatedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    taker: AddressLike,
    maker: AddressLike,
    quoteId: BytesLike,
    fromToken: AddressLike,
    toToken: AddressLike,
    fromAmount: BigNumberish,
    toAmount: BigNumberish,
    settlementTime: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    taker: string,
    maker: string,
    quoteId: string,
    fromToken: string,
    toToken: string,
    fromAmount: bigint,
    toAmount: bigint,
    settlementTime: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    taker: string;
    maker: string;
    quoteId: string;
    fromToken: string;
    toToken: string;
    fromAmount: bigint;
    toAmount: bigint;
    settlementTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeFundedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    funder: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    totalBalance: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    funder: string,
    token: string,
    amount: bigint,
    totalBalance: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    funder: string;
    token: string;
    amount: bigint;
    totalBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeRefundedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    to: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    to: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeSettledEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    settledBy: AddressLike,
    paidFrom: BigNumberish,
    paidTo: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    settledBy: string,
    paidFrom: bigint,
    paidTo: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    settledBy: string;
    paidFrom: bigint;
    paidTo: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Settlement extends BaseContract {
  connect(runner?: ContractRunner | null): Settlement;
  waitForDeployment(): Promise<this>;

  interface: SettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  batchSettle: TypedContractMethod<
    [tradeIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  cancelTrade: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTrade: TypedContractMethod<
    [
      taker: AddressLike,
      maker: AddressLike,
      fromToken: AddressLike,
      toToken: AddressLike,
      fromAmount: BigNumberish,
      toAmount: BigNumberish,
      settlementTime: BigNumberish,
      quoteId: BytesLike,
      takerSig: BytesLike,
      makerSig: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  emergencyCancel: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrowBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  fundTrade: TypedContractMethod<
    [tradeId: BigNumberish, amountToFund: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTrade: TypedContractMethod<
    [tradeId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        taker: string;
        maker: string;
        fromToken: string;
        toToken: string;
        fromAmount: bigint;
        toAmount: bigint;
        settlementTime: bigint;
        quoteId: string;
        state: bigint;
        takerBalance: bigint;
        makerBalance: bigint;
      }
    ],
    "view"
  >;

  gracePeriod: TypedContractMethod<[], [bigint], "view">;

  isExpired: TypedContractMethod<
    [t: Settlement.TradeStruct],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  quoteUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  refundIfExpired: TypedContractMethod<
    [tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  remainingToFund: TypedContractMethod<
    [tradeId: BigNumberish],
    [[bigint, bigint] & { takerRemaining: bigint; makerRemaining: bigint }],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGracePeriod: TypedContractMethod<
    [_seconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;

  tradeCounter: TypedContractMethod<[], [bigint], "view">;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        fromAmount: bigint;
        toAmount: bigint;
        settlementTime: bigint;
        taker: string;
        maker: string;
        fromToken: string;
        toToken: string;
        quoteId: string;
        state: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifySignatures: TypedContractMethod<
    [
      taker: AddressLike,
      maker: AddressLike,
      fromToken: AddressLike,
      toToken: AddressLike,
      fromAmount: BigNumberish,
      toAmount: BigNumberish,
      settlementTime: BigNumberish,
      quoteId: BytesLike,
      takerSig: BytesLike,
      makerSig: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchSettle"
  ): TypedContractMethod<[tradeIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTrade"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTrade"
  ): TypedContractMethod<
    [
      taker: AddressLike,
      maker: AddressLike,
      fromToken: AddressLike,
      toToken: AddressLike,
      fromAmount: BigNumberish,
      toAmount: BigNumberish,
      settlementTime: BigNumberish,
      quoteId: BytesLike,
      takerSig: BytesLike,
      makerSig: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyCancel"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundTrade"
  ): TypedContractMethod<
    [tradeId: BigNumberish, amountToFund: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTrade"
  ): TypedContractMethod<
    [tradeId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        taker: string;
        maker: string;
        fromToken: string;
        toToken: string;
        fromAmount: bigint;
        toAmount: bigint;
        settlementTime: bigint;
        quoteId: string;
        state: bigint;
        takerBalance: bigint;
        makerBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gracePeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[t: Settlement.TradeStruct], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "refundIfExpired"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remainingToFund"
  ): TypedContractMethod<
    [tradeId: BigNumberish],
    [[bigint, bigint] & { takerRemaining: bigint; makerRemaining: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGracePeriod"
  ): TypedContractMethod<[_seconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tradeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        fromAmount: bigint;
        toAmount: bigint;
        settlementTime: bigint;
        taker: string;
        maker: string;
        fromToken: string;
        toToken: string;
        quoteId: string;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySignatures"
  ): TypedContractMethod<
    [
      taker: AddressLike,
      maker: AddressLike,
      fromToken: AddressLike,
      toToken: AddressLike,
      fromAmount: BigNumberish,
      toAmount: BigNumberish,
      settlementTime: BigNumberish,
      quoteId: BytesLike,
      takerSig: BytesLike,
      makerSig: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettleSkipped"
  ): TypedContractEvent<
    SettleSkippedEvent.InputTuple,
    SettleSkippedEvent.OutputTuple,
    SettleSkippedEvent.OutputObject
  >;
  getEvent(
    key: "TradeCancelled"
  ): TypedContractEvent<
    TradeCancelledEvent.InputTuple,
    TradeCancelledEvent.OutputTuple,
    TradeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TradeCreated"
  ): TypedContractEvent<
    TradeCreatedEvent.InputTuple,
    TradeCreatedEvent.OutputTuple,
    TradeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeFunded"
  ): TypedContractEvent<
    TradeFundedEvent.InputTuple,
    TradeFundedEvent.OutputTuple,
    TradeFundedEvent.OutputObject
  >;
  getEvent(
    key: "TradeRefunded"
  ): TypedContractEvent<
    TradeRefundedEvent.InputTuple,
    TradeRefundedEvent.OutputTuple,
    TradeRefundedEvent.OutputObject
  >;
  getEvent(
    key: "TradeSettled"
  ): TypedContractEvent<
    TradeSettledEvent.InputTuple,
    TradeSettledEvent.OutputTuple,
    TradeSettledEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettleSkipped(uint256,string)": TypedContractEvent<
      SettleSkippedEvent.InputTuple,
      SettleSkippedEvent.OutputTuple,
      SettleSkippedEvent.OutputObject
    >;
    SettleSkipped: TypedContractEvent<
      SettleSkippedEvent.InputTuple,
      SettleSkippedEvent.OutputTuple,
      SettleSkippedEvent.OutputObject
    >;

    "TradeCancelled(uint256,address)": TypedContractEvent<
      TradeCancelledEvent.InputTuple,
      TradeCancelledEvent.OutputTuple,
      TradeCancelledEvent.OutputObject
    >;
    TradeCancelled: TypedContractEvent<
      TradeCancelledEvent.InputTuple,
      TradeCancelledEvent.OutputTuple,
      TradeCancelledEvent.OutputObject
    >;

    "TradeCreated(uint256,address,address,bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TradeCreatedEvent.InputTuple,
      TradeCreatedEvent.OutputTuple,
      TradeCreatedEvent.OutputObject
    >;
    TradeCreated: TypedContractEvent<
      TradeCreatedEvent.InputTuple,
      TradeCreatedEvent.OutputTuple,
      TradeCreatedEvent.OutputObject
    >;

    "TradeFunded(uint256,address,address,uint256,uint256)": TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;
    TradeFunded: TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;

    "TradeRefunded(uint256,address,address,uint256)": TypedContractEvent<
      TradeRefundedEvent.InputTuple,
      TradeRefundedEvent.OutputTuple,
      TradeRefundedEvent.OutputObject
    >;
    TradeRefunded: TypedContractEvent<
      TradeRefundedEvent.InputTuple,
      TradeRefundedEvent.OutputTuple,
      TradeRefundedEvent.OutputObject
    >;

    "TradeSettled(uint256,address,uint256,uint256)": TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
    TradeSettled: TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
  };
}
